FROM java:8
FROM maven:alpine
WORKDIR /app
COPY . /app
RUN mvn -v
RUN mvn clean install -DskipTests
EXPOSE 8080
ADD ./target/borrowerlender-user-services-0.0.1-SNAPSHOT.jar borrowerlender-user-services-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","borrowerlender-user-services-0.0.1-SNAPSHOT.jar"]